import { PageHeader } from '@/components/layout/page-header';
import { Section } from '@/components/docs/section';

export default function DashboardPage() {
	return (
		<div className='container mx-auto max-w-5xl py-8'>
			<PageHeader
				title='Dashboard'
				description='Service order overview and key metrics. Template page for the main application view.'
				badge='Pages'
			/>

			<Section id='about' title='About This Page'>
				<div className='rounded-lg border bg-muted/40 p-8 space-y-4'>
					<p className='text-muted-foreground'>
						This page template will be generated by AI systems using the brand
						design tokens defined in this design system. Each variant is labeled
						with the AI that created it.
					</p>
					<div className='grid grid-cols-1 sm:grid-cols-2 gap-4'>
						<div className='rounded-md border bg-background p-4 space-y-1'>
							<p className='text-xs font-medium text-muted-foreground uppercase tracking-wider'>Status</p>
							<p className='font-medium'>Awaiting generation</p>
						</div>
						<div className='rounded-md border bg-background p-4 space-y-1'>
							<p className='text-xs font-medium text-muted-foreground uppercase tracking-wider'>Variants</p>
							<p className='font-medium'>None yet</p>
						</div>
					</div>
				</div>
			</Section>

			<Section id='variants' title='Variants'>
				<div className='rounded-lg border border-dashed bg-muted/20 p-12 text-center space-y-2'>
					<p className='text-lg font-medium text-muted-foreground'>No variants generated yet</p>
					<p className='text-sm text-muted-foreground'>
						Use v0, Gemini, or Claude Code to generate dashboard variants.
						Each will be added as v1, v2, etc. with the AI name.
					</p>
				</div>
			</Section>
		</div>
	);
}
